export const ING_CREATE_REQUEST = "ING_CREATE_REQUEST";
export const ING_CREATE_SUCCESS = "ING_CREATE_SUCCESS";
export const ING_CREATE_FAIL = "ING_CREATE_FAIL";
export const ING_CREATE_RESET = "ING_CREATE_RESET";

export const ING_GET_ALL_REQUEST = "ING_GET_ALL_REQUEST";
export const ING_GET_ALL_SUCCESS = "ING_GET_ALL_SUCCESS";
export const ING_GET_ALL_FAIL = "ING_GET_ALL_FAIL";
export const ING_GET_ALL_RESET = "ING_GET_ALL_RESET";

export const ING_RECOMMENT_REQUEST = "ING_RECOMMENT_REQUEST";
export const ING_RECOMMENT_SUCCESS = "ING_RECOMMENT_SUCCESS";
export const ING_RECOMMENT_FAIL = "ING_RECOMMENT_FAIL";
export const ING_RECOMMENT_RESET = "ING_RECOMMENT_RESET";
