export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST";
export const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS";
export const ORDER_DETAIL_FAIL = "ORDER_DETAIL_FAIL";

export const ORDER_USER_ALL_REQUEST = "ORDER_USER_ALL_REQUEST";
export const ORDER_USER_ALL_SUCCESS = "ORDER_USER_ALL_SUCCESS";
export const ORDER_USER_ALL_FAIL = "ORDER_USER_ALL_FAIL";

export const ORDER_ADMIN_ALL_REQUEST = "ORDER_ADMIN_ALL_REQUEST";
export const ORDER_ADMIN_ALL_SUCCESS = "ORDER_ADMIN_ALL_SUCCESS";
export const ORDER_ADMIN_ALL_FAIL = "ORDER_ADMIN_ALL_FAIL";

export const ORDER_DELIVERED_REQUEST = "ORDER_DELIVERED_REQUEST";
export const ORDER_DELIVERED_SUCCESS = "ORDER_DELIVERED_SUCCESS";
export const ORDER_DELIVERED_RESET = "ORDER_DELIVERED_RESET";
export const ORDER_DELIVERED_FAIL = "ORDER_DELIVERED_FAIL";

export const ORDER_PAID_REQUEST = "ORDER_PAID_REQUEST";
export const ORDER_PAID_SUCCESS = "ORDER_PAID_SUCCESS";
export const ORDER_PAID_FAIL = "ORDER_PAID_FAIL";
export const ORDER_PAID_RESET = "ORDER_PAID_RESET";

export const ORDER_STATUS_REQUEST = "ORDER_STATUS_REQUEST";
export const ORDER_STATUS_SUCCESS = "ORDER_STATUS_SUCCESS";
export const ORDER_STATUS_FAIL = "ORDER_STATUS_FAIL";
export const ORDER_STATUS_RESET = "ORDER_STATUS_RESET";

export const ORDER_FILTER_REQUEST = "ORDER_FILTER_REQUEST";
export const ORDER_FILTER_SUCCESS = "ORDER_FILTER_SUCCESS";
export const ORDER_FILTER_FAIL = "ORDER_FILTER_FAIL";
export const ORDER_FILTER_RESET = "ORDER_STATUS_RESET";
