export const GET_ORDER_SHIPPER_REQUEST = "GET_ORDER_SHIPPER_REQUEST";
export const GET_ORDER_SHIPPER_SUCCESS = "GET_ORDER_SHIPPER_SUCCESS";
export const GET_ORDER_SHIPPER_FAIL = "GET_ORDER_SHIPPER_FAIL";
export const GET_ORDER_SHIPPER_RESET = "GET_ORDER_SHIPPER_RESET";

export const CHOOSE_SHIPPER_REQUEST = "CHOOSE_SHIPPER_REQUEST";
export const CHOOSE_SHIPPER_SUCCESS = "CHOOSE_SHIPPER_SUCCESS";
export const CHOOSE_SHIPPER_FAIL = "CHOOSE_SHIPPER_FAIL";

export const CHANGE_FILTER = "CHANGE_FILTER";
